# Generated by Django 4.2 on 2023-05-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VotingPoll",
            new_name="Poll",
        ),
        migrations.AddField(
            model_name="candidate",
            name="poll",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="e_voting.poll",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(null=True, upload_to="e_voting/candidates"),
        ),
    ]
