# Generated by Django 4.2.1 on 2023-05-06 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="end_time",
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name="poll",
            name="start_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name="poll",
            name="updated_end_time",
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name="poll",
            name="updated_start_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
