# Generated by Django 4.2 on 2023-05-03 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("e_voting", "0002_rename_votingpoll_poll_candidate_poll_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_votes",
                to="e_voting.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_votes",
                to="e_voting.poll",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
