# Generated by Django 4.2.1 on 2023-05-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0003_alter_poll_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
