# Generated by Django 4.2.1 on 2023-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0004_poll_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
