# Generated by Django 4.2.1 on 2023-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0005_alter_poll_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="updated_end_time",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="updated_start_time",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
