# Generated by Django 4.2.1 on 2023-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "e_voting",
            "0006_remove_poll_is_active_remove_poll_updated_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="voter",
            constraint=models.UniqueConstraint(
                fields=("user", "poll"), name="unique_voter_poll_user"
            ),
        ),
    ]
