# Generated by Django 4.2.1 on 2023-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0007_voter_unique_voter_poll_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="voter",
            name="unique_voter_poll_user",
        ),
        migrations.AddConstraint(
            model_name="voter",
            constraint=models.UniqueConstraint(
                fields=("poll",), name="unique_voter_poll"
            ),
        ),
    ]
