# Generated by Django 4.2.1 on 2023-05-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0008_remove_voter_unique_voter_poll_user_and_more"),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE e_voting_voter DROP CONSTRAINT e_voting_voter_user_id_key;'),
    ]
