# Generated by Django 4.2.1 on 2023-05-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0009_auto_20230507_1234"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="voter",
            name="unique_voter_poll",
        ),
    ]
