# Generated by Django 4.2.1 on 2023-05-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0010_remove_voter_unique_voter_poll"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="choice",
            new_name="candidate",
        ),
    ]
