# Generated by Django 4.2.1 on 2023-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_voting", "0011_rename_choice_vote_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="is_voted",
            field=models.BooleanField(default=False),
        ),
    ]
