# Generated by Django 4.2.1 on 2023-05-13 09:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-start_time", "name"]},
        ),
        migrations.AddField(
            model_name="poll",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 5, 13, 10, 53, 47, 690035),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
