# Generated by Django 4.2 on 2023-05-03 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_first_name_user_is_staff_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="voted",
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("voted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("accounts.user",),
        ),
    ]
